services:
  source_postgres: #container
    image: postgres:latest #container image
    ports:
      - "5433:5432"
    networks:
      - elt_network
    environment:
      POSTGRES_DB: source_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes: #each container can create its volume
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql #from sql/init.sql mapping to the Docker directory
  destination_postgres:
    image: postgres:latest
    ports:
      - "5434:5432"
    networks:
      - elt_network
    environment:
      POSTGRES_DB: destination_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    #no volumes needed (we don't wanna save data every time)
  
  elt_script:
    build:
      context: ./elt
      dockerfile: Dockerfile
    command: ["python", "elt_script.py"]
    networks:
      - elt_network
    depends_on: #script won't run unless these specified services finish initialising:
      - source_postgres
      - destination_db
    
networks:
  elt_network:
    driver: bridge